### ISSUE TITLE
Interactions of the same type conflict with each other.

### ISSUE THREAD

**Issue by danmane** [palantir/plottable#1209]
We need to convert all interactions to use Dispatchers so they will cease to conflict with each other.

**Comment by jtlan** [comment]
@bavardage That's one of the tricky parts here. The D3 `Zoom` and `Drag` behaviors are made up a number of event listeners, and they will interfere with each other event handlers if you attach them to something that's already listening for interactions. It's not clear how they would work with dispatchers currently, since it's not possible to namespace them.

**Comment by jtlan** [comment]
Frustratingly, this is different from #1427; #1427 is due to hitboxes covering each other, while this issue is due to multiple event handlers conflicting if they aren't namespaced.

**Comment by bavardage** [comment]
zoom and drag can at least work together - I have an interaction (which extends AbstractInteraction) which uses them both (to get the pan,zoom,select behaviour I need)

**Comment by jtlan** [comment]
Fixed for:
 - [x] `Click`
 - [ ] `DoubleClick`
 - [ ] `PanZoom`
 - [ ] `Drag`
 - [x] `Pointer`
 - [x] `Key`

**Comment by jtlan** [comment]
All `Interaction`s are powered by `Dispatcher`s now, so this is done.
