### ISSUE TITLE
Gridlines on Scale.Category

### ISSUE THREAD

**Issue by danmane** [palantir/plottable#1289]

**Comment by aicioara** [comment]
Basically the ticket reduces to rendering the grid lines on the xAxis. Do we want that? If so how?

current:
![screen shot 2015-04-21 at 12 58 38 pm](https://cloud.githubusercontent.com/assets/3248682/7261403/3ebbfc1e-e826-11e4-9d99-3b82542b0844.png)

Future (excuse my Paint skills):
![screen shot 2015-04-21-2 at 12 58 38 pm](https://cloud.githubusercontent.com/assets/3248682/7261442/9040f85a-e826-11e4-8b1d-d42f5a3daeea.png)

Question: Do we want the change? @crmorford

**Comment by aicioara** [comment]
If we decide we want that case, @jtlan and @bluong 
Fix is here. Looks a bit hacky now, because we treat it as an edge case. What do you think?
https://github.com/palantir/plottable/compare/1289fix?expand=1

Ideally, we want some sort of interface `Tickable` (or something) which both `AbstractQuantitative` and `CategoryScale` implement.

**Comment by aicioara** [comment]
Reimplemented here
https://github.com/palantir/plottable/compare/1289er?expand=1

**Comment by aicioara** [comment]
Closing... Issue is too old and poorly documented. If the feature is needed, it will be requested again and we can refer to the last PR (possibly)
