### ISSUE TITLE
Extremely poor pan and zoom performance on stacked bar charts

### ISSUE THREAD

**Issue by antonycourtney** [palantir/plottable#1576]
Pan and zoom exhibit extremely poor performance for stacked bar charts with just a few hundred points.

Here is a jsfiddle to demonstrate the issue:
http://jsfiddle.net/antonyc/w82xhLzL/7/

If you try the scroll gesture on the chart to zoom in and out, response is extremely sluggish -- hundreds of milliseconds for each redraw.

If you change from stacked bar charts to line charts for the same data set, zooming is buttery smooth.  You can try this by commenting out lines 44-49 and un-commenting lines 56-63 in the Fiddle.

**Comment by jtlan** [comment]
Hi @antonycourtney,

Thanks for bringing this up. In this case, the poor performance is due to automatic bar width calculation (filed as #1284). In this case, you can `.project()` "width" onto the bars; see http://jsfiddle.net/nggs73go/ for what that would look like (line 47). We're working on streamlining the semantics of width projection (see #1174).

Thanks for your interest in Plottable!

**Comment by antonycourtney** [comment]
@jtlan Fantastic to have that workaround...thank you!  

Just getting started with Plottable but really like it so far.  Thank you all creating and sharing it, and putting so much care and thought into the design.
