### ISSUE TITLE
[Axes.Category] Smart label truncating 

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1577]
Inspiration:
![screen shot 2015-02-04 at 3 14 44 pm](https://cloud.githubusercontent.com/assets/7527733/6051850/947afa92-ac80-11e4-9329-5bee32abd320.png)

What if instead of trying to truncate/new line long words, when the graph gets smaller, you can pass in a few alternative options to switch to.
eg. top choice for labels is [January, February, March...]
but if that doesn't fit, try [Jan, Feb, Mar, ...]
and as a last resort, use [J, F, M, A, M ...]

We talked offline and this will probably be a Q2 goal

**Comment by aicioara** [comment]
Could this be a new formatter to add? But if so, 

Edge cases: 
- How do we detect that the category scale labels are actually 
- What if user has labels like "Quarter1", "Quarter2", etc. Those should be truncated to Q1, Q2, so we need some sort of diff.
- What if the year is present as well "January 2015", "February 2015". Those should go to "J 2015", "F 2015"
- What if the months are no longer in continuous order. "J, A, J, O" Does not really sound like every 3 months

**Comment by aicioara** [comment]
Can't we just easier do it in the projector?
```typescript
plot.y(function(label) {return label.substring(0, 1).toUpperCase() }, yScale)
```

**Comment by cmslewis** [comment]
Double tapping here after commenting IRL a while ago - this bugfix would be a major value-add for me. 

**Use Case**
I'm using `Plottable.Axes.Category` with `Plottable.Plots.Bar`. With lots of bars. On a mobile device.

**Desired:**
I'd like to show a bar for each of the 24 hours in a day, on a tiny-ish mobile screen. This results in some skinny bars, though I only want to label every 3rd hour, like this:

```
[] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] []
12       3a       6a       9a       12       3p       6p       9p
```

Note that there is theoretically plenty of space to fit all of the labels, due to many of the intermediate bars being unlabeled. 

**Observed (with Plottable v1.0.0-rc6):**

When I try this on smaller screens (e.g. the iPhone 5), I'm seeing the following:

```
[] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] []
1-       3a       6a       9a       1-       3-       6-       9-
2                                   2        p        p        p
```
--

As a v1 fix, is there some way to let labels be wider than the bars with which they're associated?

**Comment by jtlan** [comment]
>As a v1 fix, is there some way to let labels be wider than the bars with which they're associated?

This already can happen, but it's hard to see when the bars are very narrow already.

**Comment by CalvinFernandez** [comment]
completed
