### ISSUE TITLE
Scale.ModifiedLog produces weird ticks under reasonable circumstances

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1762]
Setting `domain([0, 10])` will cause no ticks to appear:

http://jsfiddle.net/rtdxr3xv/

**Comment by aicioara** [comment]
Progress so far (all on 1762fix branch)
- the linear ticks in `modifiedLogScale.tick()` did not produce any ticks unless `showIntermediateTicks(true)` was invoked on the scale. Removed that limitation.
- The labels (and ticks) are no longer evenly spaced for a log scale, hence `abstractAxis._hideOverflowingTickLabels()` had to change, because at the moment there is some hack in place which just evenly spreads the labels. Removed that hack, but now will break #1196 
- Looking into http://vis.stanford.edu/files/2010-TickLabels-InfoVis.pdf as suggested by @jtlan

**Comment by aicioara** [comment]
Updated fiddle v
