### ISSUE TITLE
Adding an image at a certain point in the plot

### ISSUE THREAD

**Issue by vivianliang** [palantir/plottable#1802]
I'd like to add an image at a certain date along the x-axis and value along the y-axis. How would I do that?

**Comment by jtlan** [comment]
We don't currently have a `Component` to do this; You could attach an `<image>` tag to the foreground of a `Component` using d3, as shown here: http://jsfiddle.net/14o7rkLe/1/

We've been focusing on `Interaction`s lately, so we haven't had time to look into this. However, we'd definitely welcome a pull request to solve this in a more general way. It seems like this request goes beyond just a static image-`Component`, since its position could be data driven.

**Comment by aicioara** [comment]
Looks like it can be solved in #1894 in a more general way. Closing this particular case.

For completeness, this is the updated example http://jsfiddle.net/14o7rkLe/8/
