### ISSUE TITLE
Rectangle plots appear to need useless attributes

### ISSUE THREAD

**Issue by jtamayo** [palantir/plottable#1930]
The following code renders a rectangle plot:

            var xScale = new Plottable.Scale.Linear();
            var yScale = new Plottable.Scale.Linear();
            var plot = new Plottable.Plot.Rectangle(xScale, yScale);
            plot
                .project("x", (d) => d[0], xScale) // WHAT IS THIS FOR
                .project("y", (d) => d[2], yScale) // SAME HERE
                .project("x1", (d) => d[0], xScale)
                .project("x2", (d) => d[1], xScale)
                .project("y1", (d) => 0  , yScale)
                .project("y2", (d) => d[2], yScale);
            plot.addDataset(histogramData.buckets);
            var hist = new Plottable.Component.Table([
                [plot]
            ]).renderTo(<any> d3.select(<any> element[0]).select("svg"));

Notice the "x" and "y" attributes. As far as I can tell they are computed by `Rectangle.prototype._generateAttrToProjector`, but must be set explicitly because `AbstractXYPlot.prototype._generateAttrToProjector` depends on them. I would expect not having to set "x" and "y" on a Rectangle plot.

**Comment by rcchen** [comment]
Preface to the following comments: `Plot.Rectangle` was never intended to be used directly; it was actually created to build other plots off of it.

The reason the "x" and "y" attributes need to be projected is for the values associated on the X and Y axes. Consider the case where you're creating a `Plot.Grid`, which subclasses `Plot.Rectangle`, with `Axis.Category` on both the X and Y axes. In this scenario, the projection of "x" would be for the category you want on your plot (ie. Plain, Train, Plantain, etc.), x1 would be for the left side of the rectangle, and x2 would be for the right side of the rectangle. Likewise for the projection of "y".

We definitely questioned this for quite a bit when designing `Plot.Rectangle` and went with it because it fit within our `project()` architecture at the time the best. Over the next two weeks, we're doing a major API refactor that encompasses cleaning up how `project()` works (see #1909, #1910), so hopefully there won't be strangeness like this anymore.

**Comment by jtamayo** [comment]
OK, that meaning makes some sense. I'll leave it in there for now. I guess we should close this bug?

Thanks!

**Comment by rcchen** [comment]
We'll leave it here until it is truly fixed in the API refactor :)

**Comment by rcchen** [comment]
We blew up `.x2` and `.y2` in the API refactor; in addition, `Plots.Grid` no longer exists and its functionality has been rolled into `Plots.Rectangle`. For more information about the new usage, it landed in [v1.0.0-RC3](https://github.com/palantir/plottable/releases/tag/v1.0.0-rc3)
