### ISSUE TITLE
`Plots.Grid` x/y methods

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2062]
Currently `Plots.Grid` has 6 different methods for setting the X and Y properties:
```Typescript
x()
x1()
x2()
y()
y1()
y2()
```

Is it possible to trim this down? The user needs to be able to set the left and right sides on non-`Category` `Scales`, but should they also be able to specify the position of the data as distinct from those edges?

**Comment by rcchen** [comment]
`Plots.Grid` currently has to deal with the following scenarios:

1. category/value on both axes
  - use case: [heat map](http://en.wikipedia.org/wiki/Heat_map)
  - endpoints: `.x1`, `.y1`
  - key: (x1, y1)
2. range on the x axis, and category/value on the y axis
  - use case: [histogram](https://en.wikipedia.org/wiki/Histogram)
  - endpoints: `.x1`, `.x2`, `.y1`
  - key: (x1 x2, y1)
3. category/value on the x axis, and range on the y axis
  - use case: [waterfall chart](http://en.wikipedia.org/wiki/Waterfall_chart)
  - endpoints: `.x1`, `.y1`, `.y2`
  - key: (x1, y1 y2)
4. range on both axes
  - use case: TBD, but assuming the other three are covered, this will be covered as well
  - endpoint: `.x1`, `.x2`, `.y1`, `.y2`
  - key: (x1 x2, y1 y2)

Based on the variety of things that are going on here, here's my suggestion(s):

- Remove `Plots.Grid` and put all of its logic into `Plots.Rectangle` so that `Plots.Rectangle` is actually functional as a base class. Case 4 covers the flexibility of the original `Plots.Rectangle`.
- Standardize to four endpoints, `.x`, `.x1`, `.y`, `.y1`. We really should not be using `.x`, `.x2`, `.y`, `.y2` because where on earth are `.x1` and `.y1`? The other option is standardizing to `.x1` and `.y1` for all XY based plots, but this seems slightly worse.

@bluong how do you feel this compares to the original implementations of `Plots.Rectangle` and `Plots.Grid`?
