### ISSUE TITLE
Stacked Utils Refactor

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2262]
- [x] StackedUtils’s computeStackOffsets() should not return a d3Map and likely a Utils.Map.
- [x] StackedUtil’s computeStackExtents() has quite the number of arguments (5). Seek to reduce this.
- [x] `Utils.Stacked` -> `Utils.Stacking`

**Comment by bluong** [comment]
Side note, should these be instead called `StackingUtils`?

**Comment by aicioara** [comment]
I agree

**Comment by jtlan** [comment]
It's also possible that we could use an ordinary dictionary `Object` instead of a `Utils.Map`.

**Comment by bluong** [comment]
My main preference is to deviate from returning `D3` types in our public API as much as possible

**Comment by danmane** [comment]
The keys are potentially coming from user data right? So if you use regular objects rather than d3 maps / utils.map then it will break if the user puts in data with weird keys like "__proto__". Any time you are mapping arbitrary keys that the user provides it's not safe to put them in an object without sanitization. 
(I think the d3 map is just a wrapper to a JS object that sanitizes by prepending a string to every key.)
