### ISSUE TITLE
Drag box selection in data space rather than pixel space

### ISSUE THREAD

**Issue by christinaforney** [palantir/plottable#2475]
When selecting, have the option to select in data space rather than pixel space. Be careful with the crimp line feature here as well as log scales. 

@benduffield has some code for this, reach out to him.

**Comment by jtlan** [comment]
What's the actual ask here? The `Bounds` object can be passed through the `Scale`s to get the data-space values. `SelectionBoxLayer` was initially designed to operate in pixel-space so that it would be agnostic to the underlying `Scales`, allowing it to work with non-Quantitative `Scale`s or with multiple `Scale`s at once.

**Comment by bluong** [comment]
The example usecase that I see is this:

Let's say that I draw a `SelectionBoxLayer` onto a plot.  WIth the current architecture, if I were to use an `Interactions.PanZoom` to pan around the plot, the box in the `SelectionBoxLayer` would not move with the pan.  What might be preferred is to extend the current functionality so that the bounds of the box can update when the a pan happens

**Comment by bavardage** [comment]
Right - the pixel values are almost never useful, so everyone using it will have to write the code to pass the values through the scales anyway. Also everyone will have to write the code to keep it in sync with scales (for pan zoom, etc). Better to not force everyone to write the same code.
