### ISSUE TITLE
onKeyPress is listening to keydown event

### ISSUE THREAD

**Issue by ztsai** [palantir/plottable#2499]
as mentioned in comment in #2393, onKeyPress is fired repeatedly while the key is pressed which is a bug
```onKeyPress()``` should be listening to ```keypress``` and we should add another api for ```keydown```

**Comment by bluong** [comment]
Alternatively the dispatcher can listen and ignore successive keydown/keypress events for keys that not have been "upped" yet.

**Comment by ztsai** [comment]
there might be problems if key is released when the cursor is outside of the plot

**Comment by bluong** [comment]
I'm unsure if we need to have both a `onKeyPress` and a `onKeyDown`.  We should only have one I think

**Comment by aicioara** [comment]
I wouldn't call this a bug, but rather an expected behavior. Maybe I do not know what is the exact behavior (a fiddle would be nice), but as a (operating system) user I expect the keyboard to spam the keypress if I keep it down. 

Also, I agree with @bluong we should not have both a `onKeyPress` and `onKeyDown`
