### ISSUE TITLE
Bubble chart

### ISSUE THREAD

**Issue by mato75** [palantir/plottable#2521]
Is there an example of a bubble chart build with Plottable somewhere?

BTW
Really nice library, I like, keep up the good work.

**Comment by jtlan** [comment]
Hello @mato75 !

`Plots.Scatter` can function as a bubble chart by changing the size as a function of the data, using the `size()` API point:

```Javascript
var sizeScale = new Plottable.Scales.Linear();
sizeScale.range([0, 10]); // size in pixels; change "10" to an appropriate value as necessary
scatterPlot.size(function(d) { return d.population; }, sizeScale); 
```

Omitting the `Scale` in the above snippet will directly set size to the value of `d.population`, which may be extremely large.

The [hockey example](http://plottablejs.org/examples/hockey/) on our website shows this feature, although the differences in sizes aren't very dramatic.

**Comment by aicioara** [comment]
@jtlan Maybe this can be transformed into a plottable-website issue. Create a section of the website where we show how to make different sorts of second-class (or not so obvious) classes using the existing building blocks. 

Alternatively, we can reproduce the punch chard plot from GitHub as another example?

I feel like this issue is not the first time someone asks for help with bubble charts.

**Comment by mato75** [comment]
Yes, that would be awesome, in tutorials, or somewhere, some additional examples of different type of charts.

**Comment by mato75** [comment]
Hm, scatter sizes are all the same when used with sizeScale. 

Please check this example.
http://jsfiddle.net/mato75/1734wvs5/43/

**Comment by mato75** [comment]
sorry, will open a new issue.
