### ISSUE TITLE
More display options for labels on Plots.Bar

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2578]
Currently, labels on `Plots.Bar` are drawn within the bar itself, and are hidden if they are too small. However, it's often exactly in the circumstances of small bars that labels are most useful. It'd be good to have an option to display the labels *above* the bars instead of within them.

**Comment by jtlan** [comment]
Probably most of the difficulty here comes from how to make sure there's enough space beyond the bars to show the labels.

**Comment by aicioara** [comment]
Probably shrink the plot by exactly the height of the label (since for the tallest bar that is exactly how much we want it to shrink. 

Question: Do we want to support a mixture of inside/above the bar or we make a clear option of above/inside. The use case I can think of for the mixture is: small bars have text displayed above, tall bars have it inside. This way we don't sacrifice the height of the plot, but it might be visually weird.

**Comment by okal** [comment]
I did a quick and dirty fix on the generated JS (I don't yet speak TS) that resulted in this.

![image](https://cloud.githubusercontent.com/assets/449209/9191988/b465a3fc-400f-11e5-9ba5-196c3c433e78.png)

We're generating the ticks ourselves so we can repurpose the Bar plotting code for histograms. It also illustrates the problem we have with showing end ticks, which are pretty essential for the histogram case.

**Comment by okal** [comment]
This needed a change to Writer.prototype.writeLine to allow a configurable `"y"` attribute, FYI. I didn't dig in enough to know if setting a different offset would help. I'll explore that today.
