### ISSUE TITLE
More examples would be really helpful 

### ISSUE THREAD

**Issue by mato75** [palantir/plottable#2774]
Maybe a new folder examples, where users can push their examples or is there already a git repo with  more examples?

**Comment by karolinkaIn** [comment]
Oh yes, please!

**Comment by christinaforney** [comment]
This is where our examples currently live. If you'd like to send us a jsfiddle, plunker, or other examples, we'll quickly add them to our examples page: http://plottablejs.org/examples/

If you have any specific requests, please let us know and we'll try to get to this soon!

**Comment by crmorford** [comment]
We have a few more examples in plottable/quicktests/overlaying/tests (they're sorted into a few categories, look in the folders to find them)

1. Once inside the Plottable repo, run grunt in the terminal (just type 'grunt' and press enter):

2. Then open up a browser and go to http://localhost:9999/quicktests/overlaying/index.html
It will look like this:
![screen shot 2015-09-16 at 10 52 56 am](https://cloud.githubusercontent.com/assets/7527733/9908350/39a011e8-5c61-11e5-92a2-eb377ec09132.png)

3. Since you're just looking for examples, type #local in both branches at the top (usually this is used to compare 2 github branches for testing purposes)

4. Then, if you press the compare button, you'll see a lot more examples!
![screen shot 2015-09-16 at 10 53 20 am](https://cloud.githubusercontent.com/assets/7527733/9908389/63d05018-5c61-11e5-9e4d-aeeeb48e7c0a.png)

**Comment by karolinkaIn** [comment]
Thank you so much!

**Comment by mato75** [comment]
Thank you very very much.
