### ISSUE TITLE
How to use raw d3 to add elements to scatter plot?

### ISSUE THREAD

**Issue by ricklupton** [palantir/plottable#2828]
I can't find in the documentation anywhere how to extend components with d3, although I get the impression this is intended to be possible.

For example, in <http://plottablejs.org/examples/synchronized/>, to add a text element to the selectedPoint <g> which shows the current value.

This [wiki page](https://github.com/palantir/plottable/wiki/plot.getSelection%28%29-API-Proposal) suggests this is possible but appears to be out of date or not to have been implemented.

Thanks!

**Comment by bluong** [comment]
Hello @ricklupton !

In the example that you suggested, I took the code and placed it in a JSFiddle here:
http://jsfiddle.net/pkktrrkb/2/

If you observe the code under the comment I wrote, I made use of the `foreground()` Plottable endpoint and d3's `append()` / `selectAll()` endpoints in order to get similar behavior to what you desire.

Note that this is done inside an interaction callback and that the code makes use of the `entityNearest()` endpoint to query for the necessary information.

**Comment by ricklupton** [comment]
Thanks for the example!

For anyone else's future reference, I've modified it slightly to put the text in the correct y-position for each graph:
http://jsfiddle.net/1tthcpxL/

So I see that Components have functions `foreground()`, `content()`, and `background()`. Presumably I can use any of those as in your example, depending whether I want it behind or in front of the plot.

Can you clarify the difference between these, [`Plot.selections`](http://plottablejs.org/docs/classes/plottable.plot.html#selections) and [`PlotEntity.selection`](http://plottablejs.org/docs/interfaces/plottable.plots.plotentity.html)?

**Comment by bluong** [comment]
`Plot.selections()` is a function on the `Plot` class that will retrieve a `d3.selection` containing all of the relevant DOM elements for the plot. `PlotEntity.selection` is a parameter on the returned `PlotEntity` object that contains a `d3.selection` pertaining the relevant DOM elements for the plot in respect to how you grabbed the `PlotEntity` (using `entitiesNearest()` etc)

**Comment by crmorford** [comment]
Hey @ricklupton, I'm going to close out this issue since it seems like your problem has been resolved. Let me know if that's incorrect, and we can reopen this :)

**Comment by ricklupton** [comment]
Yes thanks!
