### ISSUE TITLE
calculating legend layout during draw is extremely slow

### ISSUE THREAD

**Issue by yocontra** [palantir/plottable#3089]
Calling redraw on a legend with 431 items locks the browser for 9 seconds. Culprit seems to be [Legend._calculateLayoutInfo](https://github.com/palantir/plottable/blob/develop/src/components/legend.ts#L162-L191)

<img width="1191" alt="screen shot 2016-07-23 at 5 44 34 pm" src="https://cloud.githubusercontent.com/assets/425716/17080433/4f3b5c10-50fd-11e6-8daf-cc922e4c0156.png">

Seems like an easy performance win to speed up draw times. Especially important since the responsive strategy for plottable is to redraw on resize events!

**Comment by jtlan** [comment]
@contra , 431 items is quite a lot for a `Legend`. Can you tell us a bit more about the use case here?

**Comment by yocontra** [comment]
@jtlan 400, 100, 10, 1 - the function is slower than it should be with all of these numbers. Use case doesn't really matter, I used a high number to demonstrate how bad the problem was. Drawing 400 things shouldn't take 9 seconds (22.5ms per item), drawing 10 shouldn't take 220ms, etc.

**Comment by teamdandelion** [comment]
@contra 
If I had to guess what's going on (just by reading the code) - it is using a text measurer to size each legend item [here](https://github.com/palantir/plottable/blob/develop/src/components/legend.ts#L171). This can be really slow because it requires actually manipulating the DOM to insert the text and then take some measurements. 

If this is indeed the slow part (should be easy to determine using console.time, or by naming the anon functions so you can look in profiler, etc) then there are a few ways to fix the performance problem. 

One is, you could implement caching for the strings. This would mean slow initial render, but fast re-compute if you are re-sizing and going for responsive design. However, if you change the css style, you would need to reset the cache.

Alternatively, you could switch the legend to use the cacheCharacterMeasurer here (https://github.com/palantir/svg-typewriter/blob/develop/src/measurers/cacheCharacterMeasurer.ts). This is a different text measurer that splits every string into individual characters, and then looks up the cached measurement for that character. It's a lot faster, won't be as accurate, but AFAIK it only over-estimates widths so it is probably fine for this application.

There are probably other solutions as well. Hope this helps.
