### ISSUE TITLE
plottable.js breaks when used standalone

### ISSUE THREAD

**Issue by hellochar** [palantir/plottable#3118]
Prior to 2.3.0 we bundled SVGTypewriter into plottable.js directly; this is no longer the case and is breaking existing users who pull in plottable standalone through a script tag. This is also breaking bower users. We should unbreak people for the time being and have a better dependency story in 3.0

**Comment by adidahiya** [comment]
I think we should make svg-typewriter more of a true dependency in the Bower world too, i.e. users are required to add a script tag for it _in addition_ to Plottable. Better to have the dependency story look the same across NPM/Bower. For now, we should tweak the webpack build to put svg-typewriter back in for the Bower distribution because we shouldn't have a breaking change in 2.x.

**Comment by CalvinFernandez** [comment]
Sigh
