### ISSUE TITLE
Position / Value over X / Y in projectors

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#898]
Having x projectors and y projectors can get ridiculously confusing when we switch to horizontal mode.  Also, it breaks the smoothness of the API as the projections need to be flipped between x and y.  Also, if users were to keep a naming convention of xScale and yScale, they would need to refactor those variables also in accordance which can cause quite a headache.  Proposition is to use position and value over x and y, somewhat respectively, and then we can deal with the differences internally.

**Comment by aicioara** [comment]
This has been discussed during the `v1.0.0` refactor. Not sure if it is documented anywhere, because most of it was whiteboard discussion. 
Objections to the proposition: 
- We don't want users to have multiple ways of achieving the same thing: Since this is an XY plot, we will have the `.x()` and `.y()` calls anyway
- Only the Plots.Bar can be flipped
- If we decide to implement this, it will be a `v2.0.0`, so a couple of months from now. Closing for now. If it is a real issue, someone will flag it again.
